export const SM_FIELDS = [
  "EXTERNAL_ID",
  "NAME",
  "NEW_PRODUCT",
  "AVABILITY",
  "BESTSELLER",
  "BRAND",
  "CATEGORIES",
  "CATEGORY_MAIN",
  "DESCRIPTION",
  "DETAIL1",
  "DETAIL2",
  "DETAIL3",
  "DETAIL4",
  "DETAIL5",
  "MANUFACTURER",
  "PRICE",
  "PRICE_PROMO",
  "QUANTITY",
  "URL_PRODUCT",
  "URL_IMAGE",
  "GENDER",
  "URL_CATEGORY",
  "URL_CATEGORY_MARK",
  "POPULARITY",
  "SEASON",
  "COLOR",
  "ADDITIONAL_IMAGE",
  "INT_DETAIL1",
  "INT_DETAIL2",
  "INT_DETAIL3",
];

export const XML_STRUCTURE = [
  "RSS/CHANNEL/ITEM",
  "PRODUCTS/PRODUCT",
  "OFFERS/OFFER",
];

export const API_FIELDS = {
  Fields: {
    id: "UNDEFINED",
    name: "UNDEFINED",
    newProductKey: "UNDEFINED",
    newProductValue: "UNDEFINED",
    availableKey: "UNDEFINED",
    availableValue: "UNDEFINED",
    bestsellerKey: "UNDEFINED",
    bestsellerValue: "UNDEFINED",
    brand: "UNDEFINED",
    categories: "UNDEFINED",
    categoryMain: "UNDEFINED",
    description: "UNDEFINED",
    detail1: "UNDEFINED",
    detail2: "UNDEFINED",
    detail3: "UNDEFINED",
    detail4: "UNDEFINED",
    detail5: "UNDEFINED",
    manufacturer: "UNDEFINED",
    price: "UNDEFINED",
    currency: "UNDEFINED",
    pricePromo: "UNDEFINED",
    quantity: "UNDEFINED",
    urlProduct: "UNDEFINED",
    urlImg: "UNDEFINED",
    genderKey: "UNDEFINED",
    genderValue: "UNDEFINED",
    urlCategory: "UNDEFINED",
    urlCategoryMark: "UNDEFINED",
    popularity: "UNDEFINED",
    season: "UNDEFINED",
    color: "UNDEFINED",
    addidtionalImage: "UNDEFINED",
    intDetail1: "UNDEFINED",
    intDetail2: "UNDEFINED",
    intDetail3: "UNDEFINED",
  },
  Mapping: {
    mapping: "UNDEFINED",
  },
  CutFields: {
    customCutLine: "UNDEFINED",
  },
  MatchFields: {
    customMatchLine: "UNDEFINED",
  },
};
